version: '3'

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  test:
    deps: [test-aws,test-cerrors,test-envlookup,test-errgroup,test-osext,test-sql-escape,test-tspb_cast,test-ulid,test-utf8bom]
  test-aws:
    dir: aws
    cmds:
      - docker compose up -d
      - defer: docker compose down
      - sleep 5
      - go test ./...
  test-cerrors:
    dir: cerrors
    cmds:
      - go test ./...
  test-envlookup:
    dir: envlookup
    cmds:
      - go test ./...
  test-errgroup:
    dir: errgroup
    cmds:
      - go test ./...
  test-osext:
    dir: osext
    cmds:
      - go test ./...
  test-sql-escape:
    dir: sql-escape
    cmds:
      - go test ./...
  test-tspb_cast:
    dir: tspb_cast
    cmds:
      - go test ./...
  test-ulid:
    dir: ulid
    cmds:
      - go test ./...
  test-utf8bom:
    dir: utf8bom
    cmds:
      - go test ./...

  go-mod-tidy:
    deps: [
      go-mod-tidy-aws,go-mod-tidy-cerrors,go-mod-tidy-envlookup,go-mod-tidy-errgroup,go-mod-tidy-osext,
      go-mod-tidy-sql-escape,go-mod-tidy-tspb_cast,go-mod-tidy-ulid,go-mod-tidy-utf8bom,
    ]
  go-mod-tidy-aws:
    dir: aws
    cmds:
      - go mod tidy
  go-mod-tidy-cerrors:
    dir: cerrors
    cmds:
      - go mod tidy
  go-mod-tidy-envlookup:
    dir: envlookup
    cmds:
      - go mod tidy
  go-mod-tidy-errgroup:
    dir: errgroup
    cmds:
      - go mod tidy
  go-mod-tidy-osext:
    dir: osext
    cmds:
      - go mod tidy
  go-mod-tidy-sql-escape:
    dir: sql-escape
    cmds:
      - go mod tidy
  go-mod-tidy-tspb_cast:
    dir: tspb_cast
    cmds:
      - go mod tidy
  go-mod-tidy-ulid:
    dir: ulid
    cmds:
      - go mod tidy
  go-mod-tidy-utf8bom:
    dir: utf8bom
    cmds:
      - go mod tidy

  go-oif:
    deps: [
      go-oif-aws,go-oif-cerrors,go-oif-envlookup,go-oif-errgroup,go-oif-osext,
      go-oif-sql-escape,go-oif-tspb_cast,go-oif-ulid,go-oif-utf8bom,
    ]
  go-oif-aws:
    dir: aws
    cmds:
      - go-oif ./...
  go-oif-cerrors:
    dir: cerrors
    cmds:
      - go-oif ./...
  go-oif-envlookup:
    dir: envlookup
    cmds:
      - go-oif ./...
  go-oif-errgroup:
    dir: errgroup
    cmds:
      - go-oif ./...
  go-oif-osext:
    dir: osext
    cmds:
      - go-oif ./...
  go-oif-sql-escape:
    dir: sql-escape
    cmds:
      - go-oif ./...
  go-oif-tspb_cast:
    dir: tspb_cast
    cmds:
      - go-oif ./...
  go-oif-ulid:
    dir: ulid
    cmds:
      - go-oif ./...
  go-oif-utf8bom:
    dir: utf8bom
    cmds:
      - go-oif ./...

  go-mod-updates:
    deps: [
      go-mod-update-aws,go-mod-update-cerrors,go-mod-update-envlookup,go-mod-update-errgroup,go-mod-update-osext,
      go-mod-update-sql-escape,go-mod-update-tspb_cast,go-mod-update-ulid,go-mod-update-utf8bom,
    ]
    cmds:
      - task go-mod-tidy
  go-mod-update-aws:
    dir: aws
    cmds:
      - go get -u ./...
  go-mod-update-cerrors:
    dir: cerrors
    cmds:
      - go get -u ./...
  go-mod-update-envlookup:
    dir: envlookup
    cmds:
      - go get -u ./...
  go-mod-update-errgroup:
    dir: errgroup
    cmds:
      - go get -u ./...
  go-mod-update-osext:
    dir: osext
    cmds:
      - go get -u ./...
  go-mod-update-sql-escape:
    dir: sql-escape
    cmds:
      - go get -u ./...
  go-mod-update-tspb_cast:
    dir: tspb_cast
    cmds:
      - go get -u ./...
  go-mod-update-ulid:
    dir: ulid
    cmds:
      - go get -u ./...
  go-mod-update-utf8bom:
    dir: utf8bom
    cmds:
      - go get -u ./...
