version: '3'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: go_utils_localstack
    ports:
      - "4566:4566" # Status
    environment:
      - AWS_ACCESS_KEY_ID=DUMMYACCESSKEYEXAMPLE
      - AWS_SECRET_ACCESS_KEY=DUMMYSECRETKEYEXAMPLE
      - AWS_DEFAULT_REGION=ap-northeast-1
      - AWS_EC2_METADATA_DISABLED=true
      - SERVICES=sqs
      - DATA_DIR=/tmp/localstack/data
      - DISABLE_CORS_CHECKS=1
      - EDGE_BIND_HOST=0.0.0.0
    volumes:
      - ./docker/localstack/init:/docker-entrypoint-initaws.d
  minio:
    image: minio/minio:latest
    container_name: go_utils_minio_ci
    ports:
      - "29000:29000"
    environment:
      - MINIO_ROOT_USER=DUMMYACCESSKEYEXAMPLE
      - MINIO_ROOT_PASSWORD=DUMMYSECRETKEYEXAMPLE
      - AWS_DEFAULT_REGION=ap-northeast-1
      - AWS_EC2_METADATA_DISABLED=true
    entrypoint: sh
    command: -c "
      minio server --address ':29000' /data;
      "
    volumes:
      - ./docker/minio/data:/data
  miniocreatebuckets:
    image: minio/mc
    container_name: go_utils_minio_init_ci
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add s3 http://minio:29000 DUMMYACCESSKEYEXAMPLE DUMMYSECRETKEYEXAMPLE;
      /usr/bin/mc --quiet mb s3/test;
      /usr/bin/mc --quiet policy set-json /policies/policy_test.json s3/test;
      exit 0;
      "
    volumes:
      - ./docker/minio/policies:/policies
