name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # (Optional) GitHub Enterprise requires GHE_HOST variable set
      #- name: Set GHE_HOST
      #  run: |
      #    echo "GHE_HOST=${GITHUB_SERVER_URL##https:\/\/}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            aws:
              - 'aws/**'
            cerrors:
              - 'cerrors/**'
            envlookup:
              - 'envlookup/**'
            errgroup:
              - 'errgroup/**'
            osext:
              - 'osext/**'
            sql-escape:
              - 'sql-escape/**'
            tspb_cast:
              - 'tspb_cast/**'
            ulid:
              - 'ulid/**'
            utf8bom:
              - 'utf8bom/**'
      - uses: release-drafter/release-drafter@v5
        if: steps.changes.outputs.aws == 'true'
        with:
          tag-prefix: aws/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@v5
        if: steps.changes.outputs.cerrors == 'true'
        with:
          tag-prefix: cerrors/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@v5
        if: steps.changes.outputs.envlookup == 'true'
        with:
          tag-prefix: envlookup/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@v5
        if: steps.changes.outputs.errgroup == 'true'
        with:
          tag-prefix: errgroup/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@v5
        if: steps.changes.outputs.osext == 'true'
        with:
          tag-prefix: osext/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@v5
        if: steps.changes.outputs.sql-escape == 'true'
        with:
          tag-prefix: sql-escape/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@v5
        if: steps.changes.outputs.tspb_cast == 'true'
        with:
          tag-prefix: tspb_cast/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@v5
        if: steps.changes.outputs.ulid == 'true'
        with:
          tag-prefix: ulid/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@v5
        if: steps.changes.outputs.utf8bom == 'true'
        with:
          tag-prefix: utf8bom/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
