name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # (Optional) GitHub Enterprise requires GHE_HOST variable set
      #- name: Set GHE_HOST
      #  run: |
      #    echo "GHE_HOST=${GITHUB_SERVER_URL##https:\/\/}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            aws:
              - 'aws/**'
            cerrors:
              - 'cerrors/**'
            envlookup:
              - 'envlookup/**'
            errgroup:
              - 'errgroup/**'
            osext:
              - 'osext/**'
            sql-escape:
              - 'sql-escape/**'
            tspb_cast:
              - 'tspb_cast/**'
            ulid:
              - 'ulid/**'
            utf8bom:
              - 'utf8bom/**'
      - uses: release-drafter/release-drafter@v5
        if: steps.changes.outputs.aws == 'true'
        with:
          name: aws/v$RESOLVED_VERSION
          tag: aws/v$RESOLVED_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@v5
        if: steps.changes.outputs.cerrors == 'true'
        with:
          name: cerrors/v$RESOLVED_VERSION
          tag: cerrors/v$RESOLVED_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@v5
        if: steps.changes.outputs.envlookup == 'true'
        with:
          name: envlookup/v$RESOLVED_VERSION
          tag: envlookup/v$RESOLVED_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@v5
        if: steps.changes.outputs.errgroup == 'true'
        with:
          name: errgroup/v$RESOLVED_VERSION
          tag: errgroup/v$RESOLVED_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@v5
        if: steps.changes.outputs.osext == 'true'
        with:
          name: osext/v$RESOLVED_VERSION
          tag: osext/v$RESOLVED_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@v5
        if: steps.changes.outputs.sql-escape == 'true'
        with:
          name: sql-escape/v$RESOLVED_VERSION
          tag: sql-escape/v$RESOLVED_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@v5
        if: steps.changes.outputs.tspb_cast == 'true'
        with:
          name: tspb_cast/v$RESOLVED_VERSION
          tag: tspb_cast/v$RESOLVED_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@v5
        if: steps.changes.outputs.ulid == 'true'
        with:
          name: ulid/v$RESOLVED_VERSION
          tag: ulid/v$RESOLVED_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@v5
        if: steps.changes.outputs.utf8bom == 'true'
        with:
          name: utf8bom/v$RESOLVED_VERSION
          tag: utf8bom/v$RESOLVED_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
