name: Release Drafter (Publish)

on:
  push:
    branches:
      - main

jobs:
  publish_release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dorny/paths-filter@9d7afb8d214ad99e78fbd4247752c4caed2b6e4c # v4.0.0
        id: changes
        with:
          filters: |
            aws:
              - 'aws/**'
            cerrors:
              - 'cerrors/**'
            emailvalidator:
                - 'emailvalidator/**'
            envlookup:
              - 'envlookup/**'
            errgroup:
              - 'errgroup/**'
            osext:
              - 'osext/**'
            sentryhelper:
              - 'sentryhelper/**'
            sql-escape:
              - 'sql-escape/**'
            tspb_cast:
              - 'tspb_cast/**'
            ulid:
              - 'ulid/**'
            utf8bom:
              - 'utf8bom/**'
            hashutil:
              - 'hashutil/**'
      - uses: release-drafter/release-drafter@6a93d829887aa2e0748befe2e808c66c0ec6e4c7 # v6.4.0
        if: steps.changes.outputs.aws == 'true'
        with:
          config-name: release-drafter-aws.yml
          name: aws/v$RESOLVED_VERSION
          tag: aws/v$RESOLVED_VERSION
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@6a93d829887aa2e0748befe2e808c66c0ec6e4c7 # v6.4.0
        if: steps.changes.outputs.cerrors == 'true'
        with:
          config-name: release-drafter-cerrors.yml
          name: cerrors/v$RESOLVED_VERSION
          tag: cerrors/v$RESOLVED_VERSION
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@6a93d829887aa2e0748befe2e808c66c0ec6e4c7 # v6.4.0
        if: steps.changes.outputs.emailvalidator == 'true'
        with:
          config-name: release-drafter-emailvalidator.yml
          name: emailvalidator/v$RESOLVED_VERSION
          tag: emailvalidator/v$RESOLVED_VERSION
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@6a93d829887aa2e0748befe2e808c66c0ec6e4c7 # v6.4.0
        if: steps.changes.outputs.envlookup == 'true'
        with:
          config-name: release-drafter-envlookup.yml
          name: envlookup/v$RESOLVED_VERSION
          tag: envlookup/v$RESOLVED_VERSION
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@6a93d829887aa2e0748befe2e808c66c0ec6e4c7 # v6.4.0
        if: steps.changes.outputs.errgroup == 'true'
        with:
          config-name: release-drafter-errgroup.yml
          name: errgroup/v$RESOLVED_VERSION
          tag: errgroup/v$RESOLVED_VERSION
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@6a93d829887aa2e0748befe2e808c66c0ec6e4c7 # v6.4.0
        if: steps.changes.outputs.osext == 'true'
        with:
          config-name: release-drafter-osext.yml
          name: osext/v$RESOLVED_VERSION
          tag: osext/v$RESOLVED_VERSION
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@6a93d829887aa2e0748befe2e808c66c0ec6e4c7 # v6.4.0
        if: steps.changes.outputs.sentryhelper == 'true'
        with:
          config-name: release-drafter-sentryhelper.yml
          name: sentryhelper/v$RESOLVED_VERSION
          tag: sentryhelper/v$RESOLVED_VERSION
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@6a93d829887aa2e0748befe2e808c66c0ec6e4c7 # v6.4.0
        if: steps.changes.outputs.sql-escape == 'true'
        with:
          config-name: release-drafter-sql-escape.yml
          name: sql-escape/v$RESOLVED_VERSION
          tag: sql-escape/v$RESOLVED_VERSION
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@6a93d829887aa2e0748befe2e808c66c0ec6e4c7 # v6.4.0
        if: steps.changes.outputs.tspb_cast == 'true'
        with:
          config-name: release-drafter-tspb_cast.yml
          name: tspb_cast/v$RESOLVED_VERSION
          tag: tspb_cast/v$RESOLVED_VERSION
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@6a93d829887aa2e0748befe2e808c66c0ec6e4c7 # v6.4.0
        if: steps.changes.outputs.ulid == 'true'
        with:
          config-name: release-drafter-ulid.yml
          name: ulid/v$RESOLVED_VERSION
          tag: ulid/v$RESOLVED_VERSION
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@6a93d829887aa2e0748befe2e808c66c0ec6e4c7 # v6.4.0
        if: steps.changes.outputs.utf8bom == 'true'
        with:
          config-name: release-drafter-utf8bom.yml
          name: utf8bom/v$RESOLVED_VERSION
          tag: utf8bom/v$RESOLVED_VERSION
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@6a93d829887aa2e0748befe2e808c66c0ec6e4c7 # v6.4.0
        if: steps.changes.outputs.hashutil == 'true'
        with:
          config-name: release-drafter-hashutil.yml
          name: hashutil/v$RESOLVED_VERSION
          tag: hashutil/v$RESOLVED_VERSION
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

