name: Test cerrors

on:
  push:
    branches:
      - main
    paths:
      - "cerrors/**"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "cerrors/**"
env:
  testdir : ./cerrors

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.23.x ]
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - name: Install Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Go Module Download
        working-directory: ${{ env.testdir }}
        run: |
          go install gotest.tools/gotestsum@latest
          go mod download

      - name: Test
        working-directory: ${{ env.testdir }}
        timeout-minutes: 3
        run: |
          # shellcheck disable=SC2046
          gotestsum --junitfile unit-tests.xml -- -v ./... -race -coverprofile="coverage.txt" -covermode=atomic -coverpkg=./...

      - uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574 # v5.4.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ env.testdir }}/coverage.txt
