name: Test UTF-8 BOM

on:
  push:
    branches:
      - main
    paths:
      - "utf8bom/**"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "utf8bom/**"
env:
  testdir : ./utf8bom

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.24.x ]
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - name: Install Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Go Module Download
        working-directory: ${{ env.testdir }}
        run: |
          go install gotest.tools/gotestsum@latest
          go mod download

      - name: Test
        working-directory: ${{ env.testdir }}
        timeout-minutes: 3
        run: |
          # shellcheck disable=SC2046
          gotestsum --junitfile unit-tests.xml -- -v ./... -race -coverprofile="coverage.txt" -covermode=atomic -coverpkg=./...

      - uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ env.testdir }}/coverage.txt
